#!/usr/bin/expect -f
set timeout 15
set host "192.168.10.207"
set user "admin1"
set pass "DigitalSm@rt"

spawn ssh -o ProxyJump=$user@14.207.128.138 -o StrictHostKeyChecking=no $user@$host
expect {
    "*assword:*" { send -- "$pass\r"; exp_continue }
    "*\$*" { }
}

send "ps aux | grep node\r"
expect "*\$*"

send "cd sso-backend && node dist/index.js\r"
expect {
    "*\$*" { }
}

send "exit\r"
expect eof
