#!/usr/bin/expect -f
set timeout 30
spawn ssh -o ProxyJump=admin1@14.207.128.138 -o StrictHostKeyChecking=no admin1@192.168.10.207
expect "admin1@14.207.128.138's password:"
send "12345678\r"
expect "admin1@192.168.10.207's password:"
send "12345678\r"
expect "$"
send "sudo systemctl status sso-backend.service -l\r"
expect "\[sudo\] password for admin1:"
send "12345678\r"
expect "$"
send "sudo journalctl -u sso-backend -n 50 --no-pager\r"
expect "$"
send "exit\r"
expect eof
