#!/usr/bin/expect -f
set timeout 300
set host "14.207.128.138"
set user "admin1"
set pass "DigitalSm@rt"

spawn scp -o StrictHostKeyChecking=no setup_nginx.sh $user@$host:/tmp/
expect "*assword:*"
send -- "$pass\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$host
expect "*assword:*"
send -- "$pass\r"
expect "*\$*"

send "echo '$pass' | sudo -S bash /tmp/setup_nginx.sh\r"
expect "*\$*"

send "exit\r"
expect eof
